apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: newnamespace-sept30-app
  namespace: custom-namespace
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/newnamespace-sept30/overlays/development
    repoURL: https://github.com/jdubrick-ai/newnamespace-sept30-gitops.git
    targetRevision: main
  destination:
    namespace: custom-namespace-app-development
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: custom-namespace
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
